//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaMedica
    {
        public int PKCita { get; set; }
        public int FKMedico { get; set; }
        public int FKEspecialidad { get; set; }
        public System.DateTime Fec_Cita { get; set; }
        public int Duracion { get; set; }
        public string Hra_Ini { get; set; }
        public string Hra_Fin { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> FKPaciente { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
