//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado()
        {
            this.Municipios = new HashSet<Municipio>();
            this.Municipios1 = new HashSet<Municipio>();
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int PkState { get; set; }
        public int FkCountry { get; set; }
        public string CveEnt { get; set; }
        public string Description { get; set; }
        public string Abrev { get; set; }
        public string CveCap { get; set; }
        public string NameCap { get; set; }
        public string PTOT { get; set; }
        public string PMAS { get; set; }
        public string PFEM { get; set; }
        public string VTOT { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual Pai Pai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Municipio> Municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Municipio> Municipios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
