//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Municipio()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int PkCity { get; set; }
        public int FkCountry { get; set; }
        public int FkState { get; set; }
        public string CveEnt { get; set; }
        public string CveCity { get; set; }
        public string Description { get; set; }
        public string CveCab { get; set; }
        public string NameCab { get; set; }
        public string PTOT { get; set; }
        public string PMAS { get; set; }
        public string PFEM { get; set; }
        public string VTOT { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Pai Pai { get; set; }
        public virtual Pai Pai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
