//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.CitaMedicas = new HashSet<CitaMedica>();
        }
    
        public int PKPaciente { get; set; }
        public string Num_Exp { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public System.DateTime Fec_Nac { get; set; }
        public int FKCountry { get; set; }
        public int FKState { get; set; }
        public int FKCity { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string Cod_Postal { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaMedica> CitaMedicas { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
